# Generated by Django 4.1.4 on 2023-04-09 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('sname', models.CharField(max_length=100)),
                ('srno', models.IntegerField(primary_key=True, serialize=False)),
                ('sadd', models.CharField(max_length=100)),
                ('sage', models.IntegerField()),
                ('smail', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cno', models.CharField(max_length=100)),
                ('cname', models.CharField(max_length=100)),
                ('cdur', models.IntegerField()),
                ('srno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.student')),
            ],
        ),
    ]
